// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpfxbshjwscrberhqpmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZnhic2hqd3NjcmJlcmhxcG1kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODI2NjgsImV4cCI6MjA3MTk1ODY2OH0.piNG3AYElKWLY3Ppx2wMrR9PGdQyIWp7vt_Y9_uff9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});